# Generated by Django 4.2.6 on 2023-10-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='avaliable_founds',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='payables',
            name='waiting_founds',
            field=models.FloatField(blank=True),
        ),
    ]
