# Generated by Django 4.2.6 on 2023-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payables_avaliable_founds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='avaliable_founds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payables',
            name='waiting_founds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
