# Generated by Django 4.2.6 on 2023-10-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payables_avaliable_founds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(help_text='1232-2222-2222-2222', max_length=18),
        ),
    ]
