# Generated by Django 4.2.6 on 2023-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(default='1232-2222-2222-2222', max_length=19),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cvv',
            field=models.CharField(default='123', max_length=3),
        ),
    ]
